name: Build OnePlus Kernel

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Device Model"
        required: true
        default: "OPAce5Pro"
      soc:
        description: "SoC"
        required: true
        default: "sm8650"
      branch:
        description: "Kernel Branch"
        required: true
        default: "oneplus/sm8650"
      manifest:
        description: "Manifest XML"
        required: true
        default: "default.xml"
      ksun_branch:
        description: "KernelSU Next Branch"
        required: true
        default: "stable"
      susfs_commit_hash_or_branch:
        description: "SusFS branch (optional)"
        required: false
        default: ""
      optimize_level:
        description: "Optimization Level"
        required: false
        default: "O2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Build and Release OnePlus Kernels
        uses: ./  # agar composite action same repo me hai
        with:
          model: ${{ inputs.model }}
          soc: ${{ inputs.soc }}
          branch: ${{ inputs.branch }}
          manifest: ${{ inputs.manifest }}
          ksun_branch: ${{ inputs.ksun_branch }}
          susfs_commit_hash_or_branch: ${{ inputs.susfs_commit_hash_or_branch }}
          optimize_level: ${{ inputs.optimize_level }}
